# Generated by Django 3.2.21 on 2023-10-15 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_friend_friend111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend111',
            new_name='Friend',
        ),
    ]
